# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conversationaudioforking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'conversationaudioforking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from downstream.proto import media_service_common_pb2 as media__service__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63onversationaudioforking.proto\x12\x1b\x63om.cisco.wcc.ccai.media.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1amedia_service_common.proto\"\xae\x02\n\x1f\x43onversationAudioForkingRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63ustomer_org_id\x18\x02 \x01(\t\x12\x37\n\x05\x61udio\x18\x03 \x01(\x0b\x32(.com.cisco.wcc.ccai.media.v1.AudioStream\x12i\n\x0f\x61\x64\x64itional_info\x18\x04 \x03(\x0b\x32P.com.cisco.wcc.ccai.media.v1.ConversationAudioForkingRequest.AdditionalInfoEntry\x1a\x35\n\x13\x41\x64\x64itionalInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xfc\x01\n\x0b\x41udioStream\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12<\n\x08\x65ncoding\x18\x02 \x01(\x0e\x32*.com.cisco.wcc.ccai.media.v1.AudioEncoding\x12\x19\n\x11sample_rate_hertz\x18\x03 \x01(\x05\x12\x33\n\x0f\x61udio_timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12:\n\x04role\x18\x05 \x01(\x0e\x32,.com.cisco.wcc.ccai.media.v1.ParticipantRole\x12\x0f\n\x07role_id\x18\x06 \x01(\t\"v\n ConversationAudioForkingResponse\x12\x16\n\x0estatus_message\x18\x01 \x01(\t\x12:\n\nerror_code\x18\x02 \x01(\x0e\x32&.com.cisco.wcc.ccai.media.v1.ErrorCode2\xb0\x01\n\x11\x43onversationAudio\x12\x9a\x01\n\x17StreamConversationAudio\x12<.com.cisco.wcc.ccai.media.v1.ConversationAudioForkingRequest\x1a=.com.cisco.wcc.ccai.media.v1.ConversationAudioForkingResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversationaudioforking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERSATIONAUDIOFORKINGREQUEST_ADDITIONALINFOENTRY']._loaded_options = None
  _globals['_CONVERSATIONAUDIOFORKINGREQUEST_ADDITIONALINFOENTRY']._serialized_options = b'8\001'
  _globals['_CONVERSATIONAUDIOFORKINGREQUEST']._serialized_start=125
  _globals['_CONVERSATIONAUDIOFORKINGREQUEST']._serialized_end=427
  _globals['_CONVERSATIONAUDIOFORKINGREQUEST_ADDITIONALINFOENTRY']._serialized_start=374
  _globals['_CONVERSATIONAUDIOFORKINGREQUEST_ADDITIONALINFOENTRY']._serialized_end=427
  _globals['_AUDIOSTREAM']._serialized_start=430
  _globals['_AUDIOSTREAM']._serialized_end=682
  _globals['_CONVERSATIONAUDIOFORKINGRESPONSE']._serialized_start=684
  _globals['_CONVERSATIONAUDIOFORKINGRESPONSE']._serialized_end=802
  _globals['_CONVERSATIONAUDIO']._serialized_start=805
  _globals['_CONVERSATIONAUDIO']._serialized_end=981
# @@protoc_insertion_point(module_scope)
