# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import conversationaudioforking_pb2 as conversationaudioforking__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in conversationaudioforking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConversationAudioStub(object):
    """Service definition for streaming agent and caller audio.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamConversationAudio = channel.stream_stream(
                '/com.cisco.wcc.ccai.media.v1.ConversationAudio/StreamConversationAudio',
                request_serializer=conversationaudioforking__pb2.ConversationAudioForkingRequest.SerializeToString,
                response_deserializer=conversationaudioforking__pb2.ConversationAudioForkingResponse.FromString,
                _registered_method=True)


class ConversationAudioServicer(object):
    """Service definition for streaming agent and caller audio.
    """

    def StreamConversationAudio(self, request_iterator, context):
        """Bidirectional streaming RPC where the client streams the audio during the call and server sends acknowledgement once per call when onComplete() is received.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationAudioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamConversationAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamConversationAudio,
                    request_deserializer=conversationaudioforking__pb2.ConversationAudioForkingRequest.FromString,
                    response_serializer=conversationaudioforking__pb2.ConversationAudioForkingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.cisco.wcc.ccai.media.v1.ConversationAudio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.cisco.wcc.ccai.media.v1.ConversationAudio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConversationAudio(object):
    """Service definition for streaming agent and caller audio.
    """

    @staticmethod
    def StreamConversationAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.cisco.wcc.ccai.media.v1.ConversationAudio/StreamConversationAudio',
            conversationaudioforking__pb2.ConversationAudioForkingRequest.SerializeToString,
            conversationaudioforking__pb2.ConversationAudioForkingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
