# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media_service_common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'media_service_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amedia_service_common.proto\x12\x1b\x63om.cisco.wcc.ccai.media.v1\"Z\n\x10InputTextContent\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12\x0e\n\x04ssml\x18\x02 \x01(\tH\x00\x12\x15\n\rlanguage_code\x18\x03 \x01(\tB\x0f\n\rinput_content*>\n\x0fParticipantRole\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\n\n\x06\x43\x41LLER\x10\x01\x12\t\n\x05\x41GENT\x10\x02*U\n\tErrorCode\x12\x0e\n\nERROR_NONE\x10\x00\x12\x1e\n\x1a\x45RROR_INVALID_AUDIO_FORMAT\x10\x01\x12\x18\n\x14\x45RROR_STREAM_FAILURE\x10\x02*C\n\rAudioEncoding\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0c\n\x08LINEAR16\x10\x01\x12\t\n\x05MULAW\x10\x02\x12\x08\n\x04\x41LAW\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_service_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARTICIPANTROLE']._serialized_start=151
  _globals['_PARTICIPANTROLE']._serialized_end=213
  _globals['_ERRORCODE']._serialized_start=215
  _globals['_ERRORCODE']._serialized_end=300
  _globals['_AUDIOENCODING']._serialized_start=302
  _globals['_AUDIOENCODING']._serialized_end=369
  _globals['_INPUTTEXTCONTENT']._serialized_start=59
  _globals['_INPUTTEXTCONTENT']._serialized_end=149
# @@protoc_insertion_point(module_scope)
